# Generated by Django 4.2 on 2024-06-14 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='OcservUser',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('group', models.CharField(default='defaults', max_length=64, unique=True)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('active', models.BooleanField(default=False)),
                ('create', models.DateField(auto_now_add=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('deactivate_date', models.DateField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                (
                    'traffic',
                    models.PositiveSmallIntegerField(
                        choices=[(1, 'free'), (2, 'monthly'), (3, 'totally')], default=2
                    ),
                ),
                ('default_traffic', models.PositiveIntegerField(default=0)),
                ('tx', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('rx', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
            ],
            options={'db_table': 'ocserv user'},
        ),
        migrations.CreateModel(
            name='MonthlyTrafficStat',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('year', models.PositiveSmallIntegerField(default=2023)),
                ('month', models.PositiveSmallIntegerField(default=1)),
                ('tx', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('rx', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user',
                        to='ocserv.ocservuser',
                    ),
                ),
            ],
            options={'db_table': 'monthly stats'},
        ),
    ]
