# Generated by Django 4.2 on 2024-06-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('ocserv', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='ocservuser',
            name='traffic',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'free'), (2, 'monthly'), (3, 'totally')], default=1
            ),
        )
    ]
