# Generated by Django 4.2 on 2024-06-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('ocserv', '0002_alter_ocservuser_traffic')]

    operations = [
        migrations.AlterField(
            model_name='ocservuser',
            name='group',
            field=models.CharField(default='defaults', max_length=64),
        )
    ]
