# Generated by Django 4.2 on 2024-06-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('ocserv', '0003_alter_ocservuser_group')]

    operations = [
        migrations.RemoveField(model_name='ocservuser', name='active'),
        migrations.AddField(
            model_name='ocservuser', name='lock', field=models.BooleanField(default=False)
        ),
    ]
