# Generated by Django 4.2 on 2024-06-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('captcha_site_key', models.TextField(blank=True, null=True)),
                ('captcha_secret_key', models.TextField(blank=True, null=True)),
                ('default_traffic', models.PositiveIntegerField(default=10)),
            ],
            options={'db_table': 'config'},
        )
    ]
